### PR TITLE
Version bump for adventure to use snapshot

### PR DESCRIPTION
**Pull request by AbhigyaKrishna**

### CODE REVIEW

**Comment by retrooper** [comment]
Do you think this will fix the adventure issues for legacy versions?

**Comment by AbhigyaKrishna** [comment]
Yeah this might fix it because they have many internal changes for parsers too

**Comment by retrooper** [comment]
Why does GitHub actions fail to build?

**Comment by derklaro** [comment]
Because the spigot sub project is unable to resolve the dependencies of the api project... The snapshot repo should be declared in the parent build file I gues...

**Comment by derklaro** [comment]
FYI they just release 4.10

**Review by retrooper — CHANGES_REQUESTED** [review]
Update to 4.10

**Comment by retrooper** [comment]
https://github.com/retrooper/packetevents/commit/65bc4e18b032150a139a66710696baaa28172995

**Pull request closed without merging**
