### PR TITLE
1.19.3 ChatMessage fix

### PR DESCRIPTION
**Pull request by AbhigyaKrishna**
retrooper asked for this

### CODE REVIEW

**Comment by retrooper** [comment]
You can only do this if the chatComponent field is empty, you can't just always do it. That defeats the purpose of that field in the protocol.

**Comment by retrooper** [comment]
Thanks for identifying the issue though.

**Comment by AbhigyaKrishna** [comment]
There is no chat component field in 1.19.3+. The body comes only with a plain text, no json message.
image

**Comment by retrooper** [comment]
There literally is, look at Unsigned Content, it is optional. If it is not present, then we must use the plain text...

**Comment by retrooper** [comment]
You can also compare with source.

**Comment by AbhigyaKrishna** [comment]
Unsigned content is also there in 1.19.1 chat message packet, along with the chat content component. I am unsure about the unsigned content being what is needed here.
image
image

**Comment by retrooper** [comment]
Let me look into 1.19.1

**Comment by retrooper** [comment]
Ok, perfect, 1.19.3+ chat components work.

**Comment by retrooper** [comment]
You undid my 1.19.3+ changes and worked on 1.19.1...

**Comment by AbhigyaKrishna** [comment]
The chat message would be processed this way so yes

**Comment by retrooper** [comment]
Why did you revert my 1.19.3 fixes?

**Comment by retrooper** [comment]
It's not correct.

**Comment by retrooper** [comment]
Why not make 1.19.1 and 1.19.3 code consistent?

**Comment by AbhigyaKrishna** [comment]
Two reason:
1. You changed the unsigned chat component field which is nullable to a not null value with the plain text.
2. The chat message would be processed this way. I have confirmed this by decompiling 1.19.1, 1.19.3 and 1.19.4.

**Pull request merged**
