### PR TITLE
Gradle, and shadow update

### PR DESCRIPTION
**Pull request by rafi67000**
I updated gradle to 8.9, and switched from `io.github.goooler.shadow` to `com.gradleup.shadow` as it's the maintained one. More info [here](https://github.com/GradleUp/shadow/issues/908)
I tested and everything compiled successfully. which you can check [here](https://github.com/rafi67000/packetevents/actions/runs/10354476371)

### CODE REVIEW

**Comment by booky10** [comment]
Your gradle update is incomplete, you additionally need to update the gradle version in `build.gradle.kts` and then run the gradle `wrapper` task

**Comment by rafi67000** [comment]
You're right sorry. I forgot about that.

**Comment by rafi67000** [comment]
ok, now it's correct xD

**Review by Bram1903 — APPROVED** [review]
LGTM

**Comment by jonesdevelopment** [comment]
lgtm

**Comment by booky10** [comment]
please update to gradle 8.10 if you find some time

**Comment by rafi67000** [comment]
> please update to gradle 8.10 if you find some time

done

**Review by booky10 — APPROVED** [review]

**Pull request merged**
