### PR TITLE
Fix error

### PR DESCRIPTION
**Pull request by LIWKK**

### CODE REVIEW

**Comment by MWHunter** [comment]
Isn’t this the same as swap item with offhand?

**Comment by LIWKK** [comment]
> 
> 
> Isn’t this the same as swap item with offhand?

nope, it's different action

**Comment by LIWKK** [comment]
> 
> 
> > Isn’t this the same as swap item with offhand?
> 
> nope, it's different action

[06:25:53] [karhu-packet-thread/WARN]: Exception in thread "karhu-packet-thread" java.lang.IllegalArgumentException: No enum constant io.github.retrooper.packetevents.packetwrappers.play.in.blockdig.WrappedPacketInBlockDig.PlayerDigType.SWAP_HELD_ITEMS
[06:25:53] [karhu-packet-thread/WARN]:     at java.lang.Enum.valueOf(Enum.java:238)
[06:25:53] [karhu-packet-thread/WARN]:     at io.github.retrooper.packetevents.packetwrappers.play.in.blockdig.WrappedPacketInBlockDig$PlayerDigType.valueOf(WrappedPacketInBlockDig.java)
[06:25:53] [karhu-packet-thread/WARN]:     at io.github.retrooper.packetevents.packetwrappers.play.in.blockdig.WrappedPacketInBlockDig.getDigType(WrappedPacketInBlockDig.java)
[06:25:53] [karhu-packet-thread/WARN]:     at me.liwk.karhu.handler.l.a(l.java)
[06:25:53] [karhu-packet-thread/WARN]:     at me.liwk.karhu.handler.l.lambda$onPacketPlayReceive$1(l.java)
[06:25:53] [karhu-packet-thread/WARN]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[06:25:53] [karhu-packet-thread/WARN]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[06:25:53] [karhu-packet-thread/WARN]:     at java.lang.Thread.run(Thread.java:748)

**Comment by MWHunter** [comment]
Adding an empty thing to an enumeration won’t fix anything.  What relationship do you have to Karhu?

**Comment by LIWKK** [comment]
Before u start wasting your time commenting my git push request

**Comment by Izibane** [comment]
> Adding an empty thing to an enumeration won’t fix anything. What relationship do you have to Karhu?

liwkk is karhu's lover 🥰

**Pull request closed without merging**
