### PR TITLE
1.21.2/1.21.3 update

### LINKED ISSUE #962: World height is wrong on join
**Describe the bug**
https://github.com/GrimAnticheat/Grim/commit/12385556503531cb0d469f30a1f6d86cec0d628a

User#getTotalWorldHeight seems to return the overworld value on join. Switching dimensions works as expected, it just seems to be on join.

**Software brand**
Paper 1.21

**Plugins**
Grim

**How To Reproduce**
Enter the nether, disconnect, join again, the world height will be wrong

**Expected behavior**
World height to return the correct values

**Screenshots**

**Additional context**

### LINKED ISSUE #1039: 1.21.3 Velocity doesn't work
**Describe the bug**
When a client try to connect with the latest Java version (1.21.3), i've a lot of errors in my console.
> Errors: https://mclo.gs/MikgEO5

**Software brand**
Velocity 3.4.0-SNAPSHOT (git-9da52f04)

**Plugins**
ajqueue, azlink, commandforward, litebans, luckperms, maintenance, maintenanceaddon, packetevents, novpn, pl-hide-pro, plan, premiumvanish, signedvelocity, spark, ultrastaffchatpro

**How To Reproduce**
1. Use the latest velocity version
2. Use the latest packetevents devbuild (https://ci.codemc.io/job/retrooper/job/packetevents/585/)
3. Use the latest client version
4. See the errors

**Expected behavior**
Client can connect with the 1.21.3 version.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by booky10**
~~Test build downloads: https://github.com/retrooper/packetevents/actions/runs/11483962127~~
This has been merged, please use https://ci.codemc.io/job/retrooper/job/packetevents/ instead.

---

~~Third snapshot was released last wednesday, so the release will probably still take some time.~~
~~Rc1 was released on thursday, so the release will probably happen next week tuesday.~~
~~This PR should be complete and ready, after testing.~~
Vanilla 1.21.2 and Spigot 1.21.2 are out, I've tested this PR on Fabric 1.21.2 and Spigot 1.21.2.
Additionally, I've tested this PR on 1.20.6, 1.16.2 and 1.8.8.

### TODO

- [x] Update all registry mappings
- [x] Update packet mappings
  - [x] Implement `WrapperPlayServerRecipeBookSettings`
  - [x] Implement every implementation of `RecipeDisplay`...
  - [x] Mark old recipe wrappers as obsolete, mojang has completely rewritten them
  - [x] Update packet serialization structures of existing packets
    - [x] ClientboundExplodePacket :(
    - [x] ClientboundPlaceGhostRecipePacket
    - [x] ClientboundPlayerPositionPacket
    - [x] ClientboundSetTimePacket
    - [x] ClientboundTeleportEntityPacket
    - [x] ClientboundUpdateRecipesPacket
    - [x] CommonPlayerSpawnInfo -> respawn packet + login packet
    - [x] ServerboundEditBookPacket limits?
    - [x] ServerboundPlaceRecipePacket
    - [x] ServerboundPlayerInputPacket
    - [x] ServerboundRecipeBookSeenRecipePacket
    - [x] ClientboundGameProfilePacket/ClientboundLoginFinishedPacket
- [x] Update block tags / item tags
- [x] early testing using on fabric
  - see https://github.com/booky10/packetevents/tree/testing/fabric-1-21-2, combines this pr + #1032 
- [x] Figure out how to handle attributes loosing their prefix
- [x] Check color nbt format for particles

---

Noteworthy changes:
- Custom recipe ingredients no longer allow for item components to be assigned, may affect something
- The player inventory or the item cursor can no longer be updated using magic numbers and normal slot change packets, this is now done with `WrapperPlayServerSetPlayerInventory` and `WrapperPlayServerSetCursorItem` respectively
  - Packetevents "transforms" incorrectly used `WrapperPlayServerSetSlot` packets to these new packets for now
- Both the `BOAT` entity type and `CHEST_BOAT` entity types have been split into separate entity types for each boat type
- Packetevents no longer defines base components of item types in code, but loads a generated version-specific definition from file

---

Fixes #1039

### CODE REVIEW

**Comment by Bram1903** [comment]
Booky on it again 💪🏻 Extremely cool to see you constantly working on the latest snapshot support, so PacketEvents supports the latest Minecraft release almost the moment it drops!

**Comment by booky10** [comment]
I've tested re-encoding all packets (especially recipes) with a fabric server and fabric client, so this PR should be ready
Should of course still be tested again after Paper (and Spigot) are done with upgrading to 1.21.2

**Comment by booky10** [comment]
1.21.2 has been released an hour ago and this PR has now been tested on Spigot 1.21.2.

**Comment by booky10** [comment]
Mojang has released 1.21.3, fixing crucial bugs, such as salmons being too small.
Tthis PR should still work fine, nothing changed on the server side - except salmons of course

**Pull request merged**
