### PR TITLE
Fix missing Equipment body slot

### LINKED ISSUE #806: [Bug] Kick when trying to lay with GSit on any slab
**Describe the bug**
Someone created an issue on my AntiHealthIndicator plugin saying that when using `/lay` with the GSit plugin, he was being kicked with the error `io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.player.EquipmentSlot.getId(com.github.retrooper.packetevents.manager.server.ServerVersion)" because the return value of "com.github.retrooper.packetevents.protocol.player.Equipment.getSlot()" is null`. I have tested this, since I wanted to make sure this wasn't an issue with my plugin, and as far as I can see it isn't. I have tested this on multiple versions, and this issue does not occur on version 1.20.4 and below. 

**Software brand**
Paper 1.20.6

**Plugins**
PacketEvents, AntiHealthIndicator, [GSit](https://www.spigotmc.org/resources/gsit-modern-sit-seat-and-chair-lay-and-crawl-plugin-1-16-1-20-6.62325/)

**How To Reproduce**
1. Listen for `ENTITY_EQUIPMENT` packets
2. Make sure it is being triggered by the `/lay` command, as generally speaking it seems to work fine
3. Re-encode it

**Expected behavior**
No trace logs ;-)

**Screenshots**
```
[20:35:02 WARN]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.player.EquipmentSlot.getId(com.github.retrooper.packetevents.manager.server.ServerVersion)" because the return value of "com.github.retrooper.packetevents.protocol.player.Equipment.getSlot()" is null
[20:35:02 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[20:35:02 WARN]:        at packetevents-spigot-2.3.1-SNAPSHOT.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[20:35:02 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[20:35:02 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[20:35:02 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[20:35:02 WARN]:        at net.minecraft.network.Connection$2.write(Connection.java:750)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[20:35:02 WARN]:        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115)
[20:35:02 WARN]:        at GSit-1.9.1.jar//dev.geco.gsit.mcv.v1_20_5_m.util.PackageUtil$1.write(PackageUtil.java:91)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
[20:35:02 WARN]:        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
[20:35:02 WARN]:        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
[20:35:02 WARN]:        at net.minecraft.network.Connection.doSendPacket(Connection.java:505)
[20:35:02 WARN]:        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:490)
[20:35:02 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[20:35:02 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[20:35:02 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[20:35:02 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[20:35:02 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[20:35:02 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:35:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:35:02 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.player.EquipmentSlot.getId(com.github.retrooper.packetevents.manager.server.ServerVersion)" because the return value of "com.github.retrooper.packetevents.protocol.player.Equipment.getSlot()" is null
[20:35:02 WARN]:        at packetevents-spigot-2.3.1-SNAPSHOT.jar//com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment.write(WrapperPlayServerEntityEquipment.java:84)
[20:35:02 WARN]:        at packetevents-spigot-2.3.1-SNAPSHOT.jar//com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:53)
[20:35:02 WARN]:        at packetevents-spigot-2.3.1-SNAPSHOT.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
[20:35:02 WARN]:        at packetevents-spigot-2.3.1-SNAPSHOT.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[20:35:02 WARN]:        at packetevents-spigot-2.3.1-SNAPSHOT.jar//io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
[20:35:02 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[20:35:02 WARN]:        ... 39 more
```

**Additional context**
This only occurs when running the `/lay` command on 1.20.5+. The above stacktrace is from Booky's custom build to add more details around an warning / error.

### PR DESCRIPTION
**Pull request by dawon**
Should fix #806.

I am not sure how to handle backward compatibility if it is needed in this case at all, as I am not sure how MC handled horse armor before 1.20.5...

### CODE REVIEW

**Comment by joshuaprince** [comment]
+1, can confirm that this fixes wrapping ENTITY_EQUIPMENT packets, and fixed horse and wolf armor causing the kick described in #806 on my 1.20.6 server. I've been running the fix without any similar issues for a few days now.

It's very easy to reproduce the original bug and show this fixes it:

```java
if (event.getPacketType() == PacketType.Play.Server.ENTITY_EQUIPMENT) {
    WrapperPlayServerEntityEquipment w = new WrapperPlayServerEntityEquipment(event);
}
```

**Comment by Bram1903** [comment]
Ahh, it was that simple! I'll test this tomorrow on 1.8 and some other versions to see how that's being dealt with. Would love for this to be fixed before the next release.

**Comment by Bram1903** [comment]
Thanks for looking into this troopah! This fixes a lot of issues I was having!

**Comment by retrooper** [comment]
No worries.

**Pull request merged**
