### PR TITLE
Adding PacketDecodeEvent

### PR DESCRIPTION
**Pull request by abhiram555**
So basically this event is added for my plugin to work. but I thought why not share it with community. you can use this event to check for BadPackets in anti-cheats or other crasher checks

### CODE REVIEW

**Comment by retrooper** [comment]
Have you tested this to work on 1.7.10 and 1.8+?

**Comment by abhiram555** [comment]
> Have you tested this to work on 1.7.10 and 1.8+?

Tested on 1.8 and 1.12 works fine

**Comment by retrooper** [comment]
Since the PacketDecodeEvent you contributed is called after the bytebuf is decompressed, We might need to call it before the decompression. We can make a separate event for when its decompressed, for example PacketDecodeEventAfterDecompress

**Comment by abhiram555** [comment]
> Since the PacketDecodeEvent you contributed is called after the bytebuf is decompressed, We might need to call it before the decompression. We can make a separate event for when its decompressed, for example PacketDecodeEventAfterDecompress

will add that.

**Comment by abhiram555** [comment]
> Since the PacketDecodeEvent you contributed is called after the bytebuf is decompressed, We might need to call it before the decompression. We can make a separate event for when its decompressed, for example PacketDecodeEventAfterDecompress

added the packet decoder before minecraft's packet decoder so yeah PacketDecodeEventAfterDecompress is not needed since you could handle compressed packet your own (by listening for SetCompressionPacket)

**Comment by abhiram555** [comment]
Added Decoder Before Minecraft's decoder in pipeline also added a getter for getting Refcnt in ByteBuffer

**Pull request merged**
