### PR TITLE
Fixed code-style

### PR DESCRIPTION
**Pull request by NoJokeFNA**

### CODE REVIEW

**Comment by retrooper** [comment]
Update on this?

**Comment by NoJokeFNA** [comment]
Well it's done 🤔 Fixed the code-style from all of my PRs

**Comment by retrooper** [comment]
Referring to "I'd keep this as getUUID(). Your PR contains conflicts and reverts my changes to your previous pull request."

**Comment by NoJokeFNA** [comment]
Done I guess

**Pull request merged**
