### PR TITLE
Added Spoof (https://spoof.abyssdev.net) support.

### PR DESCRIPTION
**Pull request by sysdm-del**
This pull request adds support for the popular Spoof plugin, where packets are not injected if a players' netty channel is instanceof a fake channel (SpoofedChannel).

### CODE REVIEW

**Comment by sysdm-del** [comment]
> Why does packetevent has to add support for a plugin and not the plugin has to add support for pe?

Because it doesn't work? It's an issue with PacketEvents' injection, they either have to add this or some bypass of some sort (silencing for example).

**Comment by NoJokeFNA** [comment]
Change it back to default Code style. If you are just changing some lines there is no need to completely change it for one single method. Removed the empty lines that you have added and everything else you have changed regarding to it.

**Comment by sysdm-del** [comment]
> Change it back to default Code style. If you are just changing some lines there is no need to completely change it for one single method. Removed the empty lines that you have added and everything else you have changed regarding to it.
Fixed

**Comment by MachineBreaker** [comment]
Why the 'Spoof' plugin can't just cancel the inject event? There's a reason for the event to exist in the first place

**Comment by AbhigyaKrishna** [comment]
I still don't get the reason behind doing this. A library plugin doesnt have to make compatibility changes for every single plugin it encounters. It defeats the purpose of a library. Instead the "Spoof plugin" should make the changes and cancel the injection of their spoof channel. A library should load before every other plugin. And if you are shadowing packetevents you should be accountable for its compatibility with other non library plugins.

**Comment by sysdm-del** [comment]
> Why the 'Spoof' plugin can't just cancel the inject event? There's a reason for the event to exist in the first place

Ah my bad, never saw this.

Closing this PR.

**Pull request closed without merging**
