### PR TITLE
'1.20 experimental features' support

### PR DESCRIPTION
**Pull request by UserNugget**

### CODE REVIEW

**Comment by Snowiiii** [comment]
Maybe this is a bit too fast would do this if 1.20 SNAPSHOT is Released

**Comment by NoJokeFNA** [comment]
What is too fast? It's a good start, nothing speaks against it?

**Comment by retrooper** [comment]
It's great to work off of something. And if you stop working on the PR I can continue with your progress. Having good communication is key here, but obviously I won't accept it yet. I can only accept it once 1.20 releases.

**Comment by MWHunter** [comment]
1.20 experimental features is the 1.19.3 datapack, it's currently in the game

**Comment by MWHunter** [comment]
How did you generate this?  I checked some if the data and it looks fine

**Comment by UserNugget** [comment]
I took this directly from decompiled Minecraft source code
I didn't generate it

**Pull request merged**
