### PR TITLE
Fix folia support

### PR DESCRIPTION
**Pull request by mani1232**

### CODE REVIEW

**Review by powercasgamer — CHANGES_REQUESTED** [review]
The `RegionizedServer` class exists..?

**Comment by mani1232** [comment]
Yes

**Comment by powercasgamer** [comment]
> Yes

Then there's no point in making this PR since the RegionizedServer class already exists.

**Comment by mani1232** [comment]
RegionizedServer not exists*

**Comment by powercasgamer** [comment]
> RegionizedServer not exists*

It does, 
image

**Comment by mani1232** [comment]
I checked, when the server is started, the plugin does not find it, I changed it everywhere in my plugins.

**Comment by powercasgamer** [comment]
> I checked, when the server is started, the plugin does not find it, I changed it everywhere in my plugins.

Can't reproduce: 
image

**Comment by mani1232** [comment]
hm...

**Pull request closed without merging**
