### PR TITLE
Update ClientVersion.java

### PR DESCRIPTION
**Pull request by terrarier2111**
Changed to correct protocolversion

### CODE REVIEW

**Comment by retrooper** [comment]
Thanks a lot, make sure you join my discord and specify your discord tag in here so I may give you the Contributor role.

**Comment by retrooper** [comment]
I give you a week.

**Comment by terrarier2111** [comment]
Whats the link to your dc?

**Comment by retrooper** [comment]
https://discord.gg/YQ8gGxQ

**Comment by terrarier2111** [comment]
This is my dc tag: JavaImpact
#1250

**Comment by retrooper** [comment]
Alrighty, done.

**Comment by retrooper** [comment]
Alrighty, done.

**Pull request merged**
