### PR TITLE
Adventure implementation

### PR DESCRIPTION
**Pull request by AbhigyaKrishna**
Adventure implementation for packet wrappers. The serialization of adventure component is platform independent.

### CODE REVIEW

**Comment by MWHunter** [comment]
fine by me if it works

**Comment by retrooper** [comment]
Noticed you try to keep our current chat abstraction, you don't need to. Adventure chat api can just replace our component system honestly. Thanks a lot @AbhigyaKrishna and I will do a few minor changes and some tests.

**Comment by AbhigyaKrishna** [comment]
I wasn't sure if i should remove the current chat serialization so i just implemented adventure on top of it

**Comment by MWHunter** [comment]
If we use implementation we need the shading plugin otherwise adventure won't actually be in the jar

**Comment by retrooper** [comment]
That is handled.

**Comment by MWHunter** [comment]
I did ./gradlew build and it didn't shade adventure into the jar

**Comment by retrooper** [comment]
Its not shaded into the API, its into Spigot jar. You are checking the api jar, aren't you?

**Comment by retrooper** [comment]
I'll see what I can do to get the libraries in the API module, cause I remember running into issues when trying to shade it into the API module, then shade the API module into spigot.

**Comment by MWHunter** [comment]
Spigot doesn't shade adventure, only paper does on 1.16+ or a version around there

**Comment by retrooper** [comment]
I know.

**Pull request merged**
