### PR TITLE
Implement nbt-serialized component types

### LINKED ISSUE #741: [Bug] WrapperPlayServerEntityEquipment issue on 1.20.5/6
**Describe the bug**
When receiving and wrapping a `WrapperPlayServerEntityEquipment` packet an `IndexOutOfBoundsException` is being thrown.

**Software brand**
Paper 1.20.6

**Plugins**
ViaVersion, test plugin

**How To Reproduce**
1. Read Entity Equipment packets and wrap them into a `WrapperPlayServerEntityEquipment` wrapper. 
2. When an item is being enchanted or damaged an error is being thrown. 

**Expected behavior**
No errors ;-)

**Strack Trace**
```
[23:44:04 WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex: 83, writerIndex: 27 (expected: 0 <= readerIndex <= writerIndex <= capacity(256))
	at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readerIndex(ByteBufOperatorModernImpl.java:44) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readerIndex(ByteBufHelper.java:39) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:583) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:571) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAdventurePredicate$PropertyMatcher.read(ItemAdventurePredicate.java:177) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1342) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1355) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAdventurePredicate$BlockPredicate.read(ItemAdventurePredicate.java:107) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1342) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1355) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.protocol.component.builtin.item.ItemAdventurePredicate.read(ItemAdventurePredicate.java:44) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.protocol.component.ComponentTypes$1.read(ComponentTypes.java:79) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:425) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:444) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment.read(WrapperPlayServerEntityEquipment.java:59) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:243) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:148) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:138) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityEquipment.<init>(WrapperPlayServerEntityEquipment.java:37) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at spigot-2.0.1-all-1714858177841.jar/com.deathmotion.antihealthindicator.packetlisteners.spoofers.EntityEquipmentListener.onPacketSend(EntityEquipmentListener.java:85) ~[spigot-2.0.1-all-1714858177841.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:44) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at 028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[028ed41fc8ad41e8d46469e5dfe320160cc8a3d6-1714858177873.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection$2.write(Connection.java:748) ~[paper-1.20.6.jar:git-Paper-38]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:503) ~[paper-1.20.6.jar:git-Paper-38]
	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:488) ~[paper-1.20.6.jar:git-Paper-38]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### PR DESCRIPTION
**Pull request by booky10**
Previously left unimplemented because I thought they weren't needed

Fixes #741

---

~~Needs testing from @Bram1903~~ done

### CODE REVIEW

**Comment by Bram1903** [comment]
# Test Rapport

## Observation 

- [x] `NullPointerException` fixed when reading nbt-serialized components.
- [x] Entity Equipment packets are still not being properly spoofed like in previous versions, but I am not sure if this PR was also meant to fix that issue.

## Conclusion 
This PR has fixed `NullPointerException` from being thrown when reading nbt-serialized components.

## Used Test Code:

```java
private final List <Enchantment> enchantmentList = Collections.singletonList(Enchantment.builder()
    .type(EnchantmentTypes.BLOCK_FORTUNE)
    .level(3)
    .build());
```

```java
WrapperPlayServerEntityEquipment packet = new WrapperPlayServerEntityEquipment(event);

List <Equipment> equipmentList = packet.getEquipment();
if (equipmentList.isEmpty()) {
    return;
}

equipmentList.forEach(equipment -> handleEquipment(equipment, packet.getClientVersion()));

packet.setEquipment(equipmentList);
event.markForReEncode(true);
```

```java
private void handleEquipment(Equipment equipment, ClientVersion clientVersion) {
    ItemStack itemStack = equipment.getItem();
    if (itemStack == null) return;

    if (itemStack.getAmount() > 1) {
        itemStack.setAmount(1);
        equipment.setItem(itemStack);
    }

    if (itemStack.isDamageableItem()) {
        if (useDamageableInterface) {
            itemStack.setDamageValue(0);
        } else {
            itemStack.setLegacyData((short) 0);
        }
        equipment.setItem(itemStack);
    }

    if (itemStack.isEnchanted(clientVersion)) {
        itemStack.setEnchantments(enchantmentList, clientVersion);
        equipment.setItem(itemStack);
    }
}
```

**Review by Bram1903 — APPROVED** [review]
See above test rapport.

**Comment by booky10** [comment]
> Entity Equipment packets are still not being properly spoofed like in previous versions, but I do not think this PR was meant to fix that issue specifically.

That should have been fixed by #745, I'll update this PR so you can test it

**Comment by Bram1903** [comment]
Everything is now working properly! Ready to be merged.

**Pull request merged**
