### PR TITLE
Update particle data to 1.20.5

### LINKED ISSUE #748: [Bug] NullPointerException when listing for Entity Metadata packets when receiving a specific particle
**Describe the bug**
When I am listening for `WrapperPlayServerEntityMetadata` packets, and I am eating an enchanted golden apple I am getting a NullPointerException.

**Software brand**
Paper 1.20.5/6

**Plugins**
ViaVersion, AntiHealthIndicator

**How To Reproduce**
1. Listen for `WrapperPlayServerEntityMetadata` packets
2. Eat an enchanted golden apple.

**Expected behavior**
No errors :-)

**Testing** 
I tracked down this error to `ParticleTypes#getById` ([Code Link](https://github.com/retrooper/packetevents/blob/2.0/api/src/main/java/com/github/retrooper/packetevents/protocol/particle/type/ParticleTypes.java#L96)), but I am too incompetent to fix it myself 😢 

image

```
[12:06:52 INFO]: [com.github.retrooper.packetevents.PacketEventsAPI] Index: 13 ID: 425983
[12:06:52 INFO]: [com.github.retrooper.packetevents.PacketEventsAPI] Type ID Map is null
```

**Stack Trace when eating an enchanted golden apple**
```
[12:05:22 WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.particle.type.ParticleType.readDataFunction()" because "type" is null
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.protocol.entity.data.EntityDataTypes.lambda$static$12(EntityDataTypes.java:154) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readCollection(PacketWrapper.java:1342) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readList(PacketWrapper.java:1355) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.protocol.entity.data.EntityDataTypes.lambda$static$30(EntityDataTypes.java:216) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readEntityMetadata(PacketWrapper.java:904) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityMetadata.read(WrapperPlayServerEntityMetadata.java:52) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:243) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:148) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:138) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityMetadata.<init>(WrapperPlayServerEntityMetadata.java:36) ~[packetevents-spigot-2.2.1.jar:?]
        at AntiHealthIndicator-2.0.1.jar/com.deathmotion.antihealthindicator.packetlisteners.spoofers.EntityMetadataListener.onPacketSend(EntityMetadataListener.java:99) ~[AntiHealthIndicator-2.0.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:44) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[packetevents-spigot-2.2.1.jar:?]
        at packetevents-spigot-2.2.1.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[packetevents-spigot-2.2.1.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at packetevents-spigot-2.2.1.jar/io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[packetevents-spigot-2.2.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection$2.write(Connection.java:748) ~[paper-1.20.6.jar:git-Paper-35]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:503) ~[paper-1.20.6.jar:git-Paper-35]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:488) ~[paper-1.20.6.jar:git-Paper-35]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### PR DESCRIPTION
**Pull request by booky10**
Also includes refactor to implement generics in particle type encoding/decoding

Fixes #748

### CODE REVIEW

**Comment by Bram1903** [comment]
Fixes #748

**Comment by retrooper** [comment]
Does not build?

**Comment by booky10** [comment]
> Does not build?

Fixed, I wasn't fully finished yet and just opened a draft PR for @Bram1903 to test

**Comment by retrooper** [comment]
If it is finished, turn it into a PR.

**Comment by booky10** [comment]
Tested to work with plugins using particles without generics

**Pull request merged**
