### PR TITLE
Added WrapperPlayServerSpawnWeatherEntity

### PR DESCRIPTION
**Pull request by NoJokeFNA**
https://wiki.vg/index.php?title=Protocol&oldid=7368#Spawn_Global_Entity
Tested Server-Versions: 1.8.8

### CODE REVIEW

**Comment by retrooper** [comment]
I might have to look into this. Can we provide some abstraction for the type and not just give the user a byte?

**Comment by NoJokeFNA** [comment]
I will take a deeper look at it today or tomorrow

**Comment by NoJokeFNA** [comment]
I don't know but does it even make much senses? (The global entity type, currently always 1 for thunderbolt) - that's what it says, so it can't really be anything else

**Review by retrooper — APPROVED** [review]
Okay. I approve.

**Comment by terrarier2111** [comment]
Thx for your great work!

**Pull request merged**
