### PR TITLE
NPE + ConcurrentModification Exception Fix

### PR DESCRIPTION
**Pull request by Aseeef**
Attempts to fix this error
```[07:35:00] [Netty Epoll Server IO #2/WARN]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:129)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.github.repooper.packetevents.Vulcan_kw.write(Vulcan_kw.java:60)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1066)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager$4.run(NetworkManager.java:215)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:750)
[07:35:00] [Netty Epoll Server IO #2/WARN]: Caused by: java.lang.NullPointerException
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at com.github.retrooper.packetevents.wrapper.PacketWrapper.writeEntityMetadata(PacketWrapper.java:686)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerSpawnPlayer.write(WrapperPlayServerSpawnPlayer.java:116)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:95)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:65)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:44)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	... 37 more
[07:35:00] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[07:35:00] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[07:35:00] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)
[07:35:00] [Netty Epoll Server IO #2/WARN]: java.nio.channels.ClosedChannelException
[07:35:00] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(...)(Unknown Source)```

### CODE REVIEW

**Comment by Aseeef** [comment]
Looking at the code, it might be some plugin misused setEntityMetadata on one of the packets. I don't see how else this NPE can happen.

**Comment by Aseeef** [comment]
Also fixing this error now
https://pastebin.com/w7z2ar3r

**Comment by Aseeef** [comment]
Also fixing this error now
https://pastebin.com/w7z2ar3r

Resolved #539

**Comment by vytskalt** [comment]
Might be better to use `ConcurrentHashMap.newKeySet()` instead of `Collections.synchronizedSet(new HashSet<>())`

**Comment by retrooper** [comment]
Yeah, I agree with @vytskalt

**Comment by Aseeef** [comment]
Done

**Comment by MWHunter** [comment]
I never knew that we supported adding and removing listeners async, but I guess as we handle reloads on the bukkit thread and packets on netty, it's sane to support this.

**Pull request merged**
