### PR TITLE
Fix NPE caused by attempting to initialize user before channel

### LINKED ISSUE #515: NPE thrown on channel initialization
**Describe the bug**
An NPE is thrown whenever a channel is initialized, causing the network to become un-connectable.

**Software**
- Velocity 3.1.2-SNAPSHOT-207 (latest dev build)
- PacketEvents `2.0` branch, commit 58df1fcc91c522cf3e3b128879dc6806f13ffa90 (the latest as of this report).
- Some Bukkit fork for 1.19.2

**Plugins**
- ViaVersion (for compatibility with 1.19.3)
- In-house, proxy-level chat and player management plugin

**How To Reproduce**
1. Shade specified PacketEvents version into plugin
2. Start proxy
3. Attempt to connect to server (incl. ping)

**Error**
```[io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0xa2808522, L:/127.0.0.1:25565 - R:/127.0.0.1:37472]
java.lang.NullPointerException: Cannot assign field "user" because "decoder" is null
	at xyz.rotmc.dimension.library.packetevents.injector.VelocityPipelineInjector.updateUser(VelocityPipelineInjector.java:102) ~[?:?]
	at xyz.rotmc.dimension.library.packetevents.manager.protocol.ProtocolManager.setUser(ProtocolManager.java:164) ~[?:?]
	at xyz.rotmc.dimension.library.packetevents.injector.ServerConnectionInitializer.initChannel(ServerConnectionInitializer.java:45) ~[?:?]
	at xyz.rotmc.dimension.library.packetevents.injector.VelocityChannelInitializer.initChannel(VelocityChannelInitializer.java:45) ~[?:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:394) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[proxy.jar:3.1.2-SNAPSHOT (git-3293f7a9-b172)]
	at java.lang.Thread.run(Thread.java:833) [?:?]```

### PR DESCRIPTION
**Pull request by wordandahalf**
Fixes #515.

### CODE REVIEW

**Comment by wordandahalf** [comment]
This was caused by the changes made in d411fe44. This rendered the library completely unusable in my experience; I'm not sure how this could go unaddressed for nearly three weeks.

**Comment by wordandahalf** [comment]
I have confirmed this working on the same software setup as specified in my ticket.

**Comment by MWHunter** [comment]
I don't test on velocity.

**Comment by SamB440** [comment]
Tested this on my Velocity proxy and it does indeed fix the issue.

**Comment by retrooper** [comment]
Thank you

**Pull request merged**
